# platform-gitops/dev/project-web-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: AppProject
metadata:
  name: web-dev
  namespace: argocd
spec:
  description: Web stack (dev)
  sourceRepos:
    - https://github.com/ronald-rmkonsult/gitops.git
  destinations:
    - server: https://kubernetes.default.svc
      namespace: "*"
  clusterResourceWhitelist:
    - group: '*'
      kind: '*'
  namespaceResourceWhitelist:
    - group: '*'
      kind: '*'
