apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: redis-dev
  namespace: infra
spec:
  generators:
  - clusters: {}
  template:
    metadata:
      name: redis-dev
      labels:
        kind: infra
    spec:
      destination:
        namespace: redis
        server: https://kubernetes.default.svc
      project: default
      source:
        path: helm/redis
        repoURL: git@github.com:ronald-rmkonsult/gitops.git
        targetRevision: main
      syncPolicy:
        syncOptions:
          - Replace=false
          - CreateNamespace=false
