apiVersion: v1
kind: Service
metadata:
  name: rollout-bluegreen-preview
spec:
  type: ClusterIP
  selector:
    app: trivial-go-web-app  
  ports:
      - port: 8080
        protocol: TCP
        targetPort: 8080

