# platform-gitops/dev/applicationsets/infra-dev.yaml
apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: infra-staging
  namespace: argocd
spec:
  generators:
    - list:
        elements:
          - name: redis
            chartPath: app-configs/services/redis
            namespace: redis
            valuesFile: values.yaml
  template:
    metadata:
      name: '{{name}}-staging'
      labels:
        app.kubernetes.io/part-of: infra
        env: staging
    spec:
      project: web-staging
      source:
        repoURL: https://github.com/ronald-rmkonsult/gitops.git
        targetRevision: main
        path: '{{chartPath}}'
        helm:
          releaseName: '{{name}}'
          valueFiles:
            - '{{valuesFile}}'
      destination:
        server: https://kubernetes.default.svc
        namespace: '{{namespace}}'
      syncPolicy:
        automated: { prune: true, selfHeal: true }
        syncOptions:
          - CreateNamespace=true
          - ApplyOutOfSyncOnly=true
